### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by a-y-u-s-h** [AnanyaSSingh/Quark2018#1]
A thread to keep a track of things to do.

**Comment by a-y-u-s-h** [comment]
# Todos :
  
- [ ] The speakers in "Guest Speakers" are now past speakers as well, all past speakers need to be at one page. 

- [ ] If Ananya approves, I think it would be better if we create a canvas based background instead of an image based. Probably something abstract like [this](https://a-y-u-s-h.github.io/experiments/126/) one or anything else. 

- [ ] Background Sound?

- [ ] "Our Team" page needs improvement.

- [ ] If possible, we must try to make new pages for "Workshops" and "Aurora Nights", it's been years and nobody changed them yet.

**Comment by a-y-u-s-h** [comment]
# Minor Bugs : 

- [ ] When one hovers on 'past speakers' icon, icon for 'sponsors' moves a little bit as well.
